---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx:      true

# Dock config
configure_dock: true
dockitems_remove: 
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'

dockeritems_persist: []

dotfiles_repo: https://github.com/Husovschi/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/Github/dotfiles
dotfiles_files:
  - .osx
  - .tmux.conf
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - ffmpeg
  - git
  - go
  - helm
  - kompose
  - terraform
  - tmux
  - youtube-dl
  - zsh-autosuggestions

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - bitwarden
  - brave-browser
  - discord
  - dozer
  - firefox
  - fluent-reader
  - google-chrome
  - mpv
  - spotify
  - stats
  - telegram
  - visual-studio-code
  - vmware-fusion

mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "sudo ~/.osx --no-restart"
