---
- hosts: all

  vars_files:
    - config.yml

  roles:

    #
    # Exterman roles 
    #
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock


    #
    # Internal roles
    #
    - role: system
      tags:
        - system


