---
###############################################################################
# General UI/UX                                                               #
###############################################################################

# Expand save panel by default
- community.general.osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true

# Save to disk (not to iCloud) by default
- community.general.osx_defaults:
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false

# Disable smart quotes as they’re annoying when typing code
- community.general.osx_defaults:
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false

# Disable smart dashes as they’re annoying when typing code
- community.general.osx_defaults:
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false

- community.general.osx_defaults:
    domain: com.apple.systemsound
    key: com.apple.sound.uiaudio.enable
    type: int
    value: 0

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

# Set a blazingly fast keyboard repeat rate, and make it happen more quickly.
- community.general.osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 10

# Disable auto-correct
- community.general.osx_defaults:
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false


###############################################################################
# Screen                                                                      #
###############################################################################

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
- community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png


###############################################################################
# Finder                                                                      #
###############################################################################

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`

- community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfDe

- community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: file:///Users/{{ ansible_env.USER }}/Desktop/

# Finder: show hidden files by default
- community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

# Finder: show all filename extensions
- community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

# Finder: show status bar
- community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

# Finder: allow text selection in Quick Look
- community.general.osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true

# Display full POSIX path as Finder window title
- community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true

# When performing a search, search the current folder by default
- community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf

# Disable the warning when changing a file extension
- community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

# Avoid creating .DS_Store files on network volumes
- community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

# Use column view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `Nlsv`, `clmv`, `Flwv`
- community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: clmv


###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################


# Make Dock icons of hidden applications translucent
- community.general.osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true