---
- user:
    name: "{{ ansible_env.USER }}"
    shell: /opt/homebrew/bin/fish
  become: yes
  when: ansible_architecture == 'arm64'

- user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/local/bin/fish
  become: yes
  when: ansible_architecture == 'x86_64'